### ISSUE TITLE
render needs default empty options hash

### ISSUE THREAD

**Issue by mooreniemi** [carlesjove/collection_json_rails#8]
Me trying to run a test case:

```
 VehiclesControllerTest#test_should_show_vehicle test » get :show, id: @vehicle

 ArgumentError: wrong number of arguments (0 for 1) from /Users/amooreniemi/.rvm/gems/ruby-2.2.2/gems/collection_json_rails-0.4.2/lib/collection_json_rails/action_controller/render.rb:4:in `render'
```

This fixes it:

```
def render(options = {})
  super options_for_render(options)
end
```

**Comment by carlesjove** [comment]
Thanks for reporting. I'll try to put up a fix release as soon as I can.

**Comment by mooreniemi** [comment]
Sure, lemme know if a PR would help.

**Comment by carlesjove** [comment]
Well, sure ;-) If you do a PR, that'd be awesome, cause I'm a bit short of time at the minute. Please, if you do provide a test case.

**Comment by mooreniemi** [comment]
np. https://github.com/carlesjove/collection_json_rails/pull/10
